// Generated by tools/convert_melonds_shaders.py from melonDS's CaptureDownscaleVS.glsl (GPL-3.0-or-later,
// Copyright 2016-2026 melonDS team). Edit the converter, not this file.
#version 450

layout(push_constant) uniform PushConstants
{
    int uInputLayer;
};

layout(location = 0) in vec2 vPosition;

layout(location = 0) smooth out vec2 fTexcoord;

void main()
{
    gl_Position = vec4((vPosition * 2.0) - 1.0, 0, 1);
    fTexcoord = vPosition;
}
