// Generated by tools/convert_melonds_shaders.py from melonDS's CaptureVS.glsl (GPL-3.0-or-later,
// Copyright 2016-2026 melonDS team). Edit the converter, not this file.
#version 450

layout(std140, set = 0, binding = 2) uniform ubCaptureConfig
{
    vec2 uInvCaptureSize;
    int uSrcALayer;
    int uSrcBLayer;
    int uSrcBOffset;
    int uDstMode;
    ivec2 uBlendFactors;
    vec4 uSrcAOffset[48];
    float uSrcBColorFactor;
};

layout(location = 0) in ivec2 vPosition;
layout(location = 1) in ivec2 vTexcoord;

layout(location = 0) smooth out vec4 fTexcoord;

void main()
{
    vec2 pos = vec2(vPosition) * uInvCaptureSize.xx;
    gl_Position = vec4((pos * 2.0) - 1.0, 0, 1);
    fTexcoord.xy = vec2(vTexcoord) / vec2(256,192);
    fTexcoord.z = float(vTexcoord.y);
    fTexcoord.w = float(vTexcoord.y + uSrcBOffset) / 256.0;
}
