// Generated by tools/convert_melonds_shaders.py from melonDS's CaptureDownscaleFS.glsl (GPL-3.0-or-later,
// Copyright 2016-2026 melonDS team). Edit the converter, not this file.
#version 450

layout(push_constant) uniform PushConstants
{
    int uInputLayer;
};

layout(set = 0, binding = 0) uniform sampler2DArray InputTex;

layout(location = 0) smooth in vec2 fTexcoord;

layout(location = 0) out vec4 oColor;

void main()
{
    ivec4 col = ivec4(texture(InputTex, vec3(fTexcoord, uInputLayer)) * 255.0);
    oColor.rgb = vec3(col.rgb >> 3) / 31.0;
    oColor.a = (col.a>0) ? 1.0 : 0.0;
}
