// Generated by tools/convert_melonds_shaders.py from melonDS's FinalPassVS.glsl (GPL-3.0-or-later,
// Copyright 2016-2026 melonDS team). Edit the converter, not this file.
#version 450

layout(std140, set = 0, binding = 3) uniform ubFinalPassConfig
{
    bvec4 uScreenSwap[48]; // one bool per scanline
    int uScaleFactor;
    int uAuxLayer;
    int uDispModeA;
    int uDispModeB;
    int uBrightModeA;
    int uBrightModeB;
    int uBrightFactorA;
    int uBrightFactorB;
    float uAuxColorFactor;
};

layout(location = 0) in vec2 vPosition;

layout(location = 0) smooth out vec3 fTexcoord;

void main()
{
    gl_Position = vec4(vPosition, 0, 1);
    fTexcoord = (vPosition.xyy + 1.0) * vec3(0.5, 0.5, 0.375);
}
