// Generated by tools/convert_melonds_shaders.py from melonDS's 2DLayerPreVS.glsl (GPL-3.0-or-later,
// Copyright 2016-2026 melonDS team). Edit the converter, not this file.
#version 450

layout(push_constant) uniform PushConstants
{
    int uCurBG;
};

struct sBGConfig
{
    ivec2 Size;
    int Type;
    int PalOffset;
    int TileOffset;
    int MapOffset;
    bool Clamp;
};

layout(std140, set = 0, binding = 2) uniform ubBGConfig
{
    int uVRAMMask;
    sBGConfig uBGConfig[4];
};


layout(location = 0) in vec2 vPosition;

layout(location = 0) smooth out vec2 fTexcoord;

void main()
{
    gl_Position = vec4((vPosition * 2.0) - 1.0, 0, 1);
    fTexcoord = vPosition * vec2(uBGConfig[uCurBG].Size);
}
