// Generated by tools/convert_melonds_shaders.py from melonDS's 2DSpritePreVS.glsl (GPL-3.0-or-later,
// Copyright 2016-2026 melonDS team). Edit the converter, not this file.
#version 450

struct sOAM
{
    ivec2 Position;
    bvec2 Flip;
    ivec2 Size;
    ivec2 BoundSize;
    int OBJMode;
    int Type;
    int PalOffset;
    int TileOffset;
    int TileStride;
    int Rotscale;
    int BGPrio;
    bool Mosaic;
};

layout(std140, set = 0, binding = 2) uniform ubSpriteConfig
{
    int uVRAMMask;
    ivec4 uRotscale[32];
    sOAM uOAM[128];
};

layout(location = 0) in ivec2 vPosition;
layout(location = 1) in int vSpriteIndex;

layout(location = 0) flat out int fSpriteIndex;
layout(location = 1) smooth out vec2 fTexcoord;

void main()
{
    ivec2 sprpos = ivec2((vSpriteIndex & 0xF) * 64, (vSpriteIndex >> 4) * 64);
    ivec2 sprsize = uOAM[vSpriteIndex].Size;
    vec2 vtxpos = vec2(sprpos) + (vec2(vPosition) * vec2(sprsize));
    vec2 fbsize = vec2(1024, 512);

    gl_Position = vec4(((vtxpos * 2.0) / fbsize) - 1.0, 0, 1);
    fSpriteIndex = vSpriteIndex;
    fTexcoord = vec2(vPosition) * vec2(sprsize);
}
