"""Converts melonDS's OpenGL 2D/compositing shaders (GLSL 1.40) to Vulkan GLSL 4.50.

Run from the repository root:  python tools/convert_melonds_shaders.py
Output goes to app/src/main/cpp/shaders/ds/ and is committed, so building needs no Python.

What changes: explicit set/binding for samplers and uniform blocks, loose uniforms become a
push-constant block, and vertex inputs / varyings / outputs get explicit locations. Shader logic
is untouched (image memory layout is the same in GL and Vulkan, so no Y flips are needed).
"""
import re, pathlib

SRC = pathlib.Path("third_party/melonDS/src/OpenGL_shaders")
DST = pathlib.Path("app/src/main/cpp/shaders/ds")

# program: (vs, fs, bindings {name: binding}, push constants [(type, name)],
#           vertex attribs {name: location}, fragment outputs {name: location})
PROGRAMS = {
    "layer_pre": ("2DLayerPreVS", "2DLayerPreFS",
                  {"VRAMTex": 0, "PalTex": 1, "ubBGConfig": 2},
                  [("int", "uCurBG")], {"vPosition": 0}, {"oColor": 0}),
    "sprite_pre": ("2DSpritePreVS", "2DSpritePreFS",
                   {"VRAMTex": 0, "PalTex": 1, "ubSpriteConfig": 2},
                   [], {"vPosition": 0, "vSpriteIndex": 1}, {"oColor": 0}),
    "sprite": ("2DSpriteVS", "2DSpriteFS",
               {"SpriteTex": 0, "Capture128Tex": 1, "Capture256Tex": 2, "ubSpriteConfig": 3,
                "ubSpriteScanlineConfig": 4},
               [("bool", "uRenderTransparent")],
               {"vPosition": 0, "vTexcoord": 1, "vSpriteIndex": 2}, {"oColor": 0, "oFlags": 1}),
    "compositor": ("2DCompositorVS", "2DCompositorFS",
                   {"BGLayerTex": 0, "OBJLayerTex": 1, "Capture128Tex": 2, "Capture256Tex": 3,
                    "MosaicTex": 4, "ubBGConfig": 5, "ubScanlineConfig": 6, "ubCompositorConfig": 7},
                   [("int", "uScaleFactor")], {"vPosition": 0}, {"oColor": 0}),
    "capture": ("CaptureVS", "CaptureFS",
                {"InputTexA": 0, "InputTexB": 1, "ubCaptureConfig": 2},
                [], {"vPosition": 0, "vTexcoord": 1}, {"oColor": 0}),
    "capture_down": ("CaptureDownscaleVS", "CaptureDownscaleFS",
                     {"InputTex": 0}, [("int", "uInputLayer")], {"vPosition": 0}, {"oColor": 0}),
    "final_pass": ("FinalPassVS", "FinalPassFS",
                   {"MainInputTexA": 0, "MainInputTexB": 1, "AuxInputTex": 2, "ubFinalPassConfig": 3},
                   [], {"vPosition": 0}, {"oTopColor": 0, "oBottomColor": 1}),
}

HEADER = ("// Generated by tools/convert_melonds_shaders.py from melonDS's {src} (GPL-3.0-or-later,\n"
          "// Copyright 2016-2026 melonDS team). Edit the converter, not this file.\n")


def convert(text, stage, bindings, push, attribs, outputs, varyings):
    text = text.replace("#version 140", "#version 450")
    lines = text.split("\n")
    out = []
    push_names = {n for _, n in push}
    for line in lines:
        s = line.strip()
        # samplers
        m = re.match(r"uniform\s+(\w+)\s+(\w+)(\[\d+\])?\s*;", s)
        if m and m.group(2) in bindings:
            out.append(f"layout(set = 0, binding = {bindings[m.group(2)]}) uniform {m.group(1)} {m.group(2)}{m.group(3) or ''};")
            continue
        # loose uniforms -> push constants (declared once below)
        if m and m.group(2) in push_names:
            continue
        # uniform blocks
        m = re.match(r"layout\(std140\)\s+uniform\s+(\w+)", s)
        if m:
            out.append(line.replace("layout(std140)", f"layout(std140, set = 0, binding = {bindings[m.group(1)]})"))
            continue
        # vertex inputs
        m = re.match(r"in\s+(\w+)\s+(\w+)\s*;", s)
        if m and stage == "vert":
            out.append(f"layout(location = {attribs[m.group(2)]}) in {m.group(1)} {m.group(2)};")
            continue
        # varyings
        m = re.match(r"((?:smooth|flat)\s+)?(in|out)\s+(\w+)\s+(\w+)\s*;", s)
        if m:
            qual, direction, typ, name = m.groups()
            if stage == "frag" and direction == "out":
                loc = outputs[name]
            else:
                loc = varyings.setdefault(name, len(varyings))
            out.append(f"layout(location = {loc}) {qual or ''}{direction} {typ} {name};")
            continue
        out.append(line)
    text = "\n".join(out)
    if push:
        block = "layout(push_constant) uniform PushConstants\n{\n" + "".join(
            f"    {t} {n};\n" for t, n in push) + "};\n"
        text = text.replace("#version 450\n", "#version 450\n\n" + block, 1)
    text = text.replace("gl_VertexID", "gl_VertexIndex")
    return text


def main():
    DST.mkdir(parents=True, exist_ok=True)
    for prog, (vs, fs, bindings, push, attribs, outputs) in PROGRAMS.items():
        varyings = {}
        for src, stage in ((vs, "vert"), (fs, "frag")):
            text = (SRC / f"{src}.glsl").read_text()
            text = convert(text, stage, bindings, push, attribs, outputs, varyings)
            (DST / f"{prog}.{stage}").write_text(HEADER.format(src=src + ".glsl") + text, newline="\n")
    print("converted", len(PROGRAMS), "programs to", DST)


if __name__ == "__main__":
    main()
