"""Converts melonDS's compute 3D renderer shaders (GPU3D_Compute_shaders.h, GLSL 4.30) into the
33 Vulkan GLSL 4.50 compute shaders the Vulkan port uses.

Run from the repository root:  python tools/convert_melonds_compute.py
Output: app/src/main/cpp/shaders/ds3d/*.comp (committed; the build compiles them to SPIR-V).

melonDS builds each shader at runtime as "#version 430" + #defines for the variant + #defines
for the screen/tile sizes + Common + the shader's source. Here:
  - the variant #defines are kept (one output file per variant, like ShaderCompileStep),
  - the size #defines become specialization constants (set per upscale factor when the
    pipeline is created), including the workgroup sizes (local_size_*_id),
  - every buffer/texture/image gets its own binding in set 0 (GL reuses numbers across types),
  - the rgba16ui image buffer of span indices is read from a storage buffer instead,
  - the four `layout(location = N) uniform`s become a push-constant block.
The shader logic itself is unchanged.
"""
import pathlib
import re

SRC = pathlib.Path("third_party/melonDS/src/GPU3D_Compute_shaders.h")
DST = pathlib.Path("app/src/main/cpp/shaders/ds3d")

# name -> list of #defines, in ShaderCompileStep order
VARIANTS = [
    ("interp_spans_z", "InterpSpans", ["InterpSpans", "ZBuffer"]),
    ("interp_spans_w", "InterpSpans", ["InterpSpans", "WBuffer"]),
    ("bin_combined", "BinCombined", ["BinCombined"]),
    ("depth_blend_z", "DepthBlend", ["DepthBlend", "ZBuffer"]),
    ("depth_blend_w", "DepthBlend", ["DepthBlend", "WBuffer"]),
]
for buf, tag in (("ZBuffer", "z"), ("WBuffer", "w")):
    for name, defs in (
        ("notex", ["NoTexture"]),
        ("notex_toon", ["NoTexture", "Toon"]),
        ("notex_highlight", ["NoTexture", "Highlight"]),
        ("tex_decal", ["UseTexture", "Decal"]),
        ("tex_modulate", ["UseTexture", "Modulate"]),
        ("tex_toon", ["UseTexture", "Toon"]),
        ("tex_highlight", ["UseTexture", "Highlight"]),
        ("shadow_mask", ["ShadowMask"]),
    ):
        VARIANTS.append((f"rasterise_{name}_{tag}", "Rasterise", ["Rasterise", buf] + defs))
VARIANTS += [
    ("clear_coarse_bin_mask", "ClearCoarseBinMask", ["ClearCoarseBinMask"]),
    ("clear_indirect_work_count", "ClearIndirectWorkCount", ["ClearIndirectWorkCount"]),
    ("calc_offsets", "CalcOffsets", ["CalculateWorkOffsets"]),
    ("sort_work", "SortWork", ["SortWork"]),
]
for i in range(8):
    defs = ["FinalPass"]
    if i & 4: defs.append("AntiAliasing")
    if i & 2: defs.append("EdgeMarking")
    if i & 1: defs.append("Fog")
    VARIANTS.append((f"final_pass_{i}", "FinalPass", defs))

SPEC_CONSTANTS = [
    (0, "ScreenWidth", 256),
    (1, "ScreenHeight", 192),
    (2, "MaxWorkTiles", 12288),
    (3, "TileSize", 8),
    (4, "CoarseTileCountY", 4),
    (5, "CoarseTileArea", 32),
    (6, "ClearCoarseBinMaskLocalSize", 64),
]

BUFFER_BINDINGS = {
    "PolygonBuffer": 0, "XSpanSetupsBuffer": 1, "YSpanSetupsBuffer": 2, "ColorTileBuffer": 3,
    "DepthTileBuffer": 4, "AttrTileBuffer": 5, "ResultBuffer": 6, "BinResultBuffer": 7,
    "WorkDescBuffer": 8, "MetaUniform": 9,
}
SAMPLER_BINDINGS = {
    "CurrentTexture": 11, "Capture128Texture": 12, "Capture256Texture": 13,
    "ClearBitmapColor": 14, "ClearBitmapDepth": 15,
}

HEADER = ("// Generated by tools/convert_melonds_compute.py from melonDS's GPU3D_Compute_shaders.h\n"
          "// (GPL-3.0-or-later, Copyright 2016-2026 melonDS team). Edit the converter, not this file.\n")


def parse_strings(text):
    """Evaluates the header's string definitions: raw literals and `A + B + R"(...)"` sums."""
    values = {}
    for m in re.finditer(r'const (?:std::string|char\*) (\w+)\s*(\{|=)', text):
        name, pos = m.group(1), m.end()
        parts = []
        while True:
            while text[pos].isspace():
                pos += 1
            if text.startswith('R"(', pos):
                end = text.index(')"', pos + 3)
                parts.append(text[pos + 3:end])
                pos = end + 2
            else:
                ident = re.match(r"\w+", text[pos:]).group(0)
                parts.append(values[ident])
                pos += len(ident)
            while text[pos].isspace():
                pos += 1
            if text[pos] == "+":
                pos += 1
                continue
            break
        values[name] = "".join(parts)
    return values


def vulkanise(src):
    # storage/uniform buffers: unique bindings in set 0
    def buf(m):
        return f"layout ({m.group(1)}, set = 0, binding = {BUFFER_BINDINGS[m.group(3)]}) {m.group(2)}{m.group(3)}"
    src = re.sub(r"layout \((std430|std140), binding = \d+\) ((?:readonly )?(?:buffer|uniform) )(\w+)", buf, src)

    # samplers
    def samp(m):
        return f"layout (set = 0, binding = {SAMPLER_BINDINGS[m.group(2)]}) uniform {m.group(1)} {m.group(2)};"
    src = re.sub(r"layout \(binding = \d+\) uniform (\w+) (\w+);", samp, src)

    # output image
    src = src.replace("layout (binding = 0, rgba8) writeonly uniform image2D FinalFB;",
                      "layout (set = 0, binding = 16, rgba8) writeonly uniform image2D FinalFB;")

    # span indices: rgba16ui image buffer -> storage buffer of packed u16x4
    src = src.replace(
        "layout (binding = 0, rgba16ui) uniform readonly uimageBuffer SetupIndices;",
        "layout (std430, set = 0, binding = 10) readonly buffer SetupIndicesBuffer\n{\n    uvec2 SetupIndicesData[];\n};\n\n"
        "uvec4 LoadSetupIndex(int i)\n{\n    uvec2 v = SetupIndicesData[i];\n"
        "    return uvec4(v.x & 0xFFFFu, v.x >> 16, v.y & 0xFFFFu, v.y >> 16);\n}")
    src = re.sub(r"imageLoad\(SetupIndices, ([^;]+?)\);", r"LoadSetupIndex(\1);", src)

    # loose uniforms -> push constants
    uniforms = re.findall(r"layout \(location = \d+\) uniform (\w+) (\w+);", src)
    if uniforms:
        src = re.sub(r"layout \(location = \d+\) uniform \w+ \w+;\n", "", src)
        # std430 push-constant layout: scalars first, then the vec2 (8-byte aligned)
        order = sorted(uniforms, key=lambda u: 1 if u[0].startswith("vec") else 0)
        block = "layout (push_constant) uniform PushConstants\n{\n" + "".join(
            f"    {t} {n};\n" for t, n in order) + "};\n"
        src = block + src

    # workgroup sizes from specialization constants
    ids = {name: cid for cid, name, _ in SPEC_CONSTANTS}
    src = src.replace("layout (local_size_x = TileSize, local_size_y = TileSize) in;",
                      f"layout (local_size_x_id = {ids['TileSize']}, local_size_y_id = {ids['TileSize']}) in;")
    src = src.replace("layout (local_size_x = ClearCoarseBinMaskLocalSize) in;",
                      f"layout (local_size_x_id = {ids['ClearCoarseBinMaskLocalSize']}) in;")
    src = src.replace("layout (local_size_x = CoarseTileArea) in;",
                      f"layout (local_size_x_id = {ids['CoarseTileArea']}) in;")
    assert "uimageBuffer" not in src and "location =" not in src
    return src


def main():
    values = parse_strings(SRC.read_text())
    DST.mkdir(parents=True, exist_ok=True)
    spec = "".join(f"layout (constant_id = {cid}) const int {name} = {default};\n"
                   for cid, name, default in SPEC_CONSTANTS)
    for out_name, source_name, defines in VARIANTS:
        text = "#version 450\n" + "".join(f"#define {d}\n" for d in defines)
        text += spec
        body = values["Common"] + values[source_name]
        text += vulkanise(body)
        (DST / f"{out_name}.comp").write_text(HEADER + text, newline="\n")
    print("wrote", len(VARIANTS), "shaders to", DST)


if __name__ == "__main__":
    main()
